name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      # https://github.com/subosito/flutter-action
      - name: CIジョブを動かすためのflutterの環境構築
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: 正常にインストールできているかを確認
        run: flutter --version

      - name: パッケージのインストール
        run: flutter pub get

      - name: テスト実行
        run: flutter test 

